### ISSUE TITLE
Remove broken Student Handbook link

### ISSUE THREAD

**Issue by wilsoliama** [CarletonComputerScienceSociety/carletoncomputersciencesociety.github.io#45]
Resources tab -> Student Handbook

**Comment by EricBellamy** [comment]
I believe this was fixed by someone else, i'm assuming that it was part of the dropdown menu. Otherwise I also looked at each page of the resource tab and couldn't find any mention of it.

<img width="223" alt="screen shot 2018-09-04 at 12 28 31 pm" src="https://user-images.githubusercontent.com/7343076/45044461-2af59a80-b03e-11e8-8bfc-dcf031a8e14d.png">
<img width="150" alt="screen shot 2018-09-04 at 12 28 56 pm" src="https://user-images.githubusercontent.com/7343076/45044463-2c26c780-b03e-11e8-9b6f-c591ff64b2d4.png">

Those are the new tab layouts on Desktop & Mobile that I used for reference.
